Move up initialization of ELEVENLABS_API_KEY
Without this, when running `python app.py`, it crashes on the first ask attempt like so:

```
Traceback (most recent call last):                                                                                                                                                                                                                                                File "/Users/jlfwong/code/hugh/app.py", line 82, in generate_audio                                                                                                                                                                                                                voice_id = next(filter(lambda v: v["name"] == ELEVENLABS_VOICE_NAME, voices))["voice_id"]                                                                                                                                                                                   StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jlfwong/code/hugh/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jlfwong/code/hugh/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jlfwong/code/hugh/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jlfwong/code/hugh/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/jlfwong/code/hugh/app.py", line 131, in ask
    generate_audio(reply, output_path=reply_path)
  File "/Users/jlfwong/code/hugh/app.py", line 84, in generate_audio
    voice_id = voices[0]["voice_id"]
IndexError: list index out of range
```

This happens because the `app.run()` call is blocking, so the initialization never happens